### ISSUE TITLE
Download page has an  old link.

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc-site#15]
view install instructions for linux leads to https://boinc.berkeley.edu/wiki/Installing_on_Linux instead of https://boinc.berkeley.edu/linux_install.php
![image](https://github.com/BOINC/boinc-site/assets/8822292/74f65dbb-b5f5-4e8e-833d-1929e17402a5)

**Comment by davidpanderson** [comment]
Fixed - thanks.
